export default [
  "Farmer'S Bounty",
  "From The Farm",
  "From The Farmer",
  "Fresh Harvest",
  "Morning Harvest",
  "Word On The Beet",
  "Urban Farm",
  "Friendly Farmers",
  "Heavenly Harvest",
  "Farm Fresh",
  "Farm Fed",
  "Farmer'S Finds",
  "Founding Farmers",
  "Found And Farmed",
  "Provisional Produce",
  "Fresh-Grown Gold",
  "Golden Fields",
  "Golden Harvest",
  "Happy Harvest",
  "Roots Market",
  "Field Fresh Market",
  "Proper Produce",
  "Main Street Market",
  "Make Your Market",
  "Farm Fresh",
  "Farm Fam",
  "Fresh Off The Farm",
  "Funny Farm",
  "Farm Hands",
  "Fat Farm",
  "Farm to Table",
  "Farm Family",
  "Family Farm",
  "Farm To Fork",
  "Farm For You",
  "Back To Nature",
  "All Fresh Markets",
  "Fresh Pick Market",
  "Farm To Mart",
  "Farm Affair Market",
  "Prime Market",
  "Green Label Mart",
  "Rooted Food Mart",
  "Open Garden Mart",
  "Farmers Go Mart",
];
